DROP DATABASE IF EXISTS movies;
CREATE DATABASE movies;
USE movies;

DROP TABLE IF EXISTS movies;

CREATE TABLE IF NOT EXISTS movies(
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  TITLE VARCHAR(100) NOT NULL,
  Popularity DECIMAL(7, 2),
  release_date DATE,
  Watched VARCHAR(10)
)



