DROP DATABASE IF EXISTS movies;
CREATE DATABASE movies;
USE movies;

DROP TABLE IF EXISTS (`MOVIES`);

CREATE TABLE movies (
  `TITLE` VARCHAR(255) NOT NULL,
  `Popularity` DECIMAL(7, 2) NULL DEFAULT NULL,
  `Date` DATE NULL DEFAULT NULL,
  `Watched` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`Title`)
)

